In [95]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, classification_report

In [96]:

df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [97]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [98]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [99]:
df.shape

(16, 4)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   soil_moisture   16 non-null     float64
 1   temperature_c   16 non-null     int64
 2   sunlight_hours  16 non-null     int64
 3   needs_water     16 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 644.0 bytes

In [101]:
df.describe()

       soil_moisture  temperature_c  sunlight_hours  needs_water
count      16.000000      16.000000       16.000000    16.000000
mean        0.341875      26.937500        7.125000     0.500000
std         0.224298       5.297405        3.304038     0.516398
min         0.050000      19.000000        1.000000     0.000000
25%         0.172500      22.000000        4.750000     0.000000
50%         0.285000      27.000000        8.000000     0.500000
75%         0.475000      30.750000        9.250000     1.000000
max         0.800000      35.000000       12.000000     1.000000

In [102]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [103]:
X_scaled = MinMaxScaler().fit_transform(X)

In [104]:
X_scaled

array([[0.06666667, 0.9375    , 0.72727273],
       [0.13333333, 0.6875    , 0.63636364],
       [0.2       , 0.4375    , 0.54545455],
       [0.26666667, 0.1875    , 0.27272727],
       [0.46666667, 0.5625    , 0.63636364],
       [0.73333333, 0.6875    , 0.81818182],
       [0.4       , 0.        , 0.18181818],
       [0.17333333, 0.1875    , 0.81818182],
       [0.53333333, 1.        , 1.        ],
       [0.        , 0.3125    , 0.36363636],
       [1.        , 0.875     , 0.72727273],
       [0.29333333, 0.875     , 0.90909091],
       [0.66666667, 0.125     , 0.09090909],
       [0.86666667, 0.375     , 0.45454545],
       [0.09333333, 0.0625    , 0.        ],
       [0.33333333, 0.625     , 0.72727273]])

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42,stratify=y)

In [106]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [107]:
# from tensorflow.keras import optimizers
# opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)

In [108]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [ ]:
# history_full = model.fit(X_train, y_train.values.reshape(-1, 1), epochs=100, batch_size=len(X_train), verbose=1) //standart full batch training

history = model.fit(
    X_train, y_train.values.reshape(-1, 1),
    validation_data = (X_test, y_test.values.reshape(-1, 1)),
    epochs = 100, batch_size = 1 , verbose = 1 
) ## mini-batch training with batch size of 1 (stochastic gradient descent)

# history_minibatch = model.fit(X_train, y_train.values.reshape(-1, 1), epochs=100, batch_size=100, verbose=1) # mini-batch training with batch size of 100 (which is larger than the training set, effectively making it full batch)`

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.5000 - loss: 0.6601 - val_accuracy: 0.5000 - val_loss: 0.6814
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5000 - loss: 0.6557 - val_accuracy: 0.5000 - val_loss: 0.6786
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6520 - val_accuracy: 0.5000 - val_loss: 0.6766
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5833 - loss: 0.6484 - val_accuracy: 0.5000 - val_loss: 0.6746
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6450 - val_accuracy: 0.7500 - val_loss: 0.6728
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6417 - val_accuracy: 0.7500 - val_loss: 0.6708
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6388 - val_accuracy: 0.7500 - val_loss: 0.6690
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6361 - val_accuracy: 0.7500 - val_loss: 0.6667
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6333 - val_accuracy: 0.7500 - val_loss: 0.6645
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6305 - val_accuracy: 0.7500 - val_loss: 0.6623
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6277 - val_accuracy: 0.7500 - val_loss: 0.6600
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6249 - val_accuracy: 0.7500 - val_loss: 0.6579
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6222 - val_accuracy: 0.7500 - val_loss: 0.6556
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6193 - val_accuracy: 0.7500 - val_loss: 0.6533
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6162 - val_accuracy: 0.7500 - val_loss: 0.6511
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6133 - val_accuracy: 0.7500 - val_loss: 0.6494
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6103 - val_accuracy: 0.7500 - val_loss: 0.6478
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6073 - val_accuracy: 0.7500 - val_loss: 0.6458
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6043 - val_accuracy: 0.7500 - val_loss: 0.6446
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.6014 - val_accuracy: 0.7500 - val_loss: 0.6429
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5980 - val_accuracy: 0.7500 - val_loss: 0.6412
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5944 - val_accuracy: 0.7500 - val_loss: 0.6384
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.5909 - val_accuracy: 0.7500 - val_loss: 0.6358
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5876 - val_accuracy: 0.7500 - val_loss: 0.6334
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5849 - val_accuracy: 1.0000 - val_loss: 0.6309
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5821 - val_accuracy: 1.0000 - val_loss: 0.6288
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5797 - val_accuracy: 1.0000 - val_loss: 0.6267
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5771 - val_accuracy: 1.0000 - val_loss: 0.6243
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5747 - val_accuracy: 1.0000 - val_loss: 0.6219
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6667 - loss: 0.5721 - val_accuracy: 0.7500 - val_loss: 0.6194
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5692 - val_accuracy: 1.0000 - val_loss: 0.6171
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5669 - val_accuracy: 0.7500 - val_loss: 0.6146
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5641 - val_accuracy: 0.7500 - val_loss: 0.6123
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5615 - val_accuracy: 0.7500 - val_loss: 0.6101
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.5593 - val_accuracy: 0.7500 - val_loss: 0.6077
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5568 - val_accuracy: 0.7500 - val_loss: 0.6052
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5545 - val_accuracy: 0.7500 - val_loss: 0.6030
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5520 - val_accuracy: 0.7500 - val_loss: 0.6006
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5496 - val_accuracy: 0.7500 - val_loss: 0.5982
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5471 - val_accuracy: 0.7500 - val_loss: 0.5959
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7500 - loss: 0.5449 - val_accuracy: 0.7500 - val_loss: 0.5934
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5424 - val_accuracy: 0.7500 - val_loss: 0.5909
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5399 - val_accuracy: 0.7500 - val_loss: 0.5885
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5375 - val_accuracy: 0.7500 - val_loss: 0.5860
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7500 - loss: 0.5350 - val_accuracy: 0.7500 - val_loss: 0.5835
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5325 - val_accuracy: 1.0000 - val_loss: 0.5811
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5302 - val_accuracy: 1.0000 - val_loss: 0.5786
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5277 - val_accuracy: 1.0000 - val_loss: 0.5760
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5251 - val_accuracy: 1.0000 - val_loss: 0.5737
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.5222 - val_accuracy: 1.0000 - val_loss: 0.5714
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5204 - val_accuracy: 1.0000 - val_loss: 0.5688
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7500 - loss: 0.5178 - val_accuracy: 1.0000 - val_loss: 0.5661
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5150 - val_accuracy: 1.0000 - val_loss: 0.5637
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8333 - loss: 0.5127 - val_accuracy: 1.0000 - val_loss: 0.5609
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.5100 - val_accuracy: 1.0000 - val_loss: 0.5581
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.5073 - val_accuracy: 1.0000 - val_loss: 0.5553
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.5045 - val_accuracy: 1.0000 - val_loss: 0.5527
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.5016 - val_accuracy: 1.0000 - val_loss: 0.5496
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4995 - val_accuracy: 1.0000 - val_loss: 0.5469
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4970 - val_accuracy: 1.0000 - val_loss: 0.5441
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4944 - val_accuracy: 1.0000 - val_loss: 0.5414
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4918 - val_accuracy: 1.0000 - val_loss: 0.5387
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4896 - val_accuracy: 1.0000 - val_loss: 0.5357
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4869 - val_accuracy: 1.0000 - val_loss: 0.5329
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4846 - val_accuracy: 1.0000 - val_loss: 0.5298
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4820 - val_accuracy: 1.0000 - val_loss: 0.5270
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4794 - val_accuracy: 1.0000 - val_loss: 0.5238
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4769 - val_accuracy: 1.0000 - val_loss: 0.5206
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9167 - loss: 0.4748 - val_accuracy: 1.0000 - val_loss: 0.5177
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - loss: 0.4722 - val_accuracy: 1.0000 - val_loss: 0.5146
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.4698 - val_accuracy: 1.0000 - val_loss: 0.5117
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.4671 - val_accuracy: 1.0000 - val_loss: 0.5088
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9167 - loss: 0.4645 - val_accuracy: 1.0000 - val_loss: 0.5057
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.4614 - val_accuracy: 1.0000 - val_loss: 0.5027
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4580 - val_accuracy: 1.0000 - val_loss: 0.4993
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.4541 - val_accuracy: 1.0000 - val_loss: 0.4961
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.4503 - val_accuracy: 1.0000 - val_loss: 0.4926
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9167 - loss: 0.4469 - val_accuracy: 1.0000 - val_loss: 0.4894
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4429 - val_accuracy: 1.0000 - val_loss: 0.4866
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4402 - val_accuracy: 1.0000 - val_loss: 0.4832
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4367 - val_accuracy: 1.0000 - val_loss: 0.4803
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4341 - val_accuracy: 1.0000 - val_loss: 0.4771
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4306 - val_accuracy: 1.0000 - val_loss: 0.4741
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4282 - val_accuracy: 1.0000 - val_loss: 0.4708
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4258 - val_accuracy: 1.0000 - val_loss: 0.4678
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4230 - val_accuracy: 1.0000 - val_loss: 0.4650
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4206 - val_accuracy: 1.0000 - val_loss: 0.4618
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9167 - loss: 0.4175 - val_accuracy: 1.0000 - val_loss: 0.4585
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4156 - val_accuracy: 1.0000 - val_loss: 0.4555
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4133 - val_accuracy: 1.0000 - val_loss: 0.4526
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4107 - val_accuracy: 1.0000 - val_loss: 0.4496
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.4082 - val_accuracy: 1.0000 - val_loss: 0.4465
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4060 - val_accuracy: 1.0000 - val_loss: 0.4436
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4032 - val_accuracy: 1.0000 - val_loss: 0.4411
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.4011 - val_accuracy: 1.0000 - val_loss: 0.4383
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3988 - val_accuracy: 1.0000 - val_loss: 0.4357
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9167 - loss: 0.3958 - val_accuracy: 1.0000 - val_loss: 0.4334
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.3946 - val_accuracy: 1.0000 - val_loss: 0.4305
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9167 - loss: 0.3924 - val_accuracy: 1.0000 - val_loss: 0.4275
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9167 - loss: 0.3895 - val_accuracy: 1.0000 - val_loss: 0.4242